# Package Overview
package_name: survival_predictor

# Data Files
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: model
pipeline_save_file: model_output_v

features:
  - pclass
  - sex
  - age
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

alpha: 0.001

vars_to_drop:
  - name
  - ticket
  - boat
  - body
  - home.dest

numerical_vars:
  - age
  - fare

categorical_vars:
  - sex
  - cabin
  - embarked
  - title

vars_to_extract_letter:
  - cabin
